/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/xtremetest.glb --types 
*/

import * as THREE from 'three'
//import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useEffect, useRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1005: THREE.Mesh
    Mesh_1005_1: THREE.Mesh
    bronze_parts: THREE.Mesh
    button_left: THREE.Mesh
    button_right: THREE.Mesh
    Circle002: THREE.Mesh
    Circle002_1: THREE.Mesh
    chrome_parts: THREE.Mesh
    drl_inside: THREE.Mesh
    Mesh_25009: THREE.Mesh
    Mesh_25009_1: THREE.Mesh
    Mesh_25009_2: THREE.Mesh
    Mesh_25009_3: THREE.Mesh
    front_disc_brake: THREE.Mesh
    front_left_shock: THREE.Mesh
    front_right_shock: THREE.Mesh
    front_tyre_sidewall: THREE.Mesh
    front_tyre_threads: THREE.Mesh
    headlight_assembly_black: THREE.Mesh
    headlight_glass: THREE.Mesh
    headlight_emission: THREE.Mesh
    headlight_part_1: THREE.Mesh
    headlight_part_3: THREE.Mesh
    hero_black_left: THREE.Mesh
    hero_black_right: THREE.Mesh
    Mesh_25006: THREE.Mesh
    Mesh_25006_1: THREE.Mesh
    Mesh_25006_2: THREE.Mesh
    number_plate_front: THREE.Mesh
    number_plate_rear: THREE.Mesh
    rear_sporcket: THREE.Mesh
    mono_shock_suspension: THREE.Mesh
    rear_swing_arm_parts: THREE.Mesh
    rear_tyre_sidewall: THREE.Mesh
    rear_tyre_thread: THREE.Mesh
    red_resevoir: THREE.Mesh
    Mesh_25008: THREE.Mesh
    Mesh_25008_1: THREE.Mesh
    rims: THREE.Mesh
    seat: THREE.Mesh
    silver_parts: THREE.Mesh
    Mesh_8001: THREE.Mesh
    Mesh_8001_1: THREE.Mesh
    Mesh_8001_2: THREE.Mesh
    Mesh_8001_3: THREE.Mesh
    tail_light_glass: THREE.Mesh
    tail_light_inside: THREE.Mesh
    taillight: THREE.Mesh
    tank: THREE.Mesh
    mirror: THREE.Mesh
    black_parts_2: THREE.Mesh
    muffler_cover: THREE.Mesh
    Rear_tyre_side_cover: THREE.Mesh
    rear_guard_inside: THREE.Mesh
    rear_mud_guard: THREE.Mesh
    exhaust_pipe: THREE.Mesh
    black_parts_3: THREE.Mesh
    black_parts_5: THREE.Mesh
    black_parts_4: THREE.Mesh
    single_channel_abs: THREE.Mesh
    indicator_led: THREE.Mesh
    tailight_emission: THREE.Mesh
    BSurfaceMesh034: THREE.Mesh
    BSurfaceMesh034_1: THREE.Mesh
    BSurfaceMesh034_2: THREE.Mesh
    BSurfaceMesh034_3: THREE.Mesh
    BSurfaceMesh034_4: THREE.Mesh
    BSurfaceMesh034_5: THREE.Mesh
    BSurfaceMesh034_6: THREE.Mesh
    BSurfaceMesh034_7: THREE.Mesh
    BSurfaceMesh034_8: THREE.Mesh
    BSurfaceMesh034_9: THREE.Mesh
    black_parts_1: THREE.Mesh
  }
  materials: {
    ['bolt silver']: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    ['light bronze']: THREE.MeshStandardMaterial
    buttons: THREE.MeshStandardMaterial
    ['engine red']: THREE.MeshStandardMaterial
    ['chain colour 2']: THREE.MeshPhysicalMaterial
    ['chain colour 1']: THREE.MeshPhysicalMaterial
    chrome: THREE.MeshStandardMaterial
    ['drl 1']: THREE.MeshStandardMaterial
    ['engine black']: THREE.MeshStandardMaterial
    ['engine silver']: THREE.MeshStandardMaterial
    resevoir_glass: THREE.MeshPhysicalMaterial
    ['front disc']: THREE.MeshStandardMaterial
    ['black fork left']: THREE.MeshStandardMaterial
    ['black fork right']: THREE.MeshStandardMaterial
    ['front tyre side wall']: THREE.MeshStandardMaterial
    ['front tyre thread']: THREE.MeshStandardMaterial
    ['headlight glass']: THREE.MeshStandardMaterial
    ['lens light off']: THREE.MeshStandardMaterial
    ['black hero left']: THREE.MeshStandardMaterial
    ['black hero right']: THREE.MeshStandardMaterial
    ['number plate']: THREE.MeshStandardMaterial
    ['rear sprocket']: THREE.MeshStandardMaterial
    ['sprint white']: THREE.MeshStandardMaterial
    ['rear tyre side wall']: THREE.MeshStandardMaterial
    ['rear tyre thread']: THREE.MeshStandardMaterial
    ['red resevoir']: THREE.MeshStandardMaterial
    ['side reflector']: THREE.MeshStandardMaterial
    grey: THREE.MeshStandardMaterial
    ['seat grey']: THREE.MeshStandardMaterial
    foot_peg: THREE.MeshStandardMaterial
    ['speedo glass']: THREE.MeshStandardMaterial
    speedometer: THREE.MeshStandardMaterial
    ['speedo black']: THREE.MeshStandardMaterial
    ['tail light']: THREE.MeshStandardMaterial
    ['tail light red']: THREE.MeshStandardMaterial
    ['tailight black']: THREE.MeshStandardMaterial
    ['TANK BLACK']: THREE.MeshStandardMaterial
    mirror: THREE.MeshStandardMaterial
    ['black 3']: THREE.MeshStandardMaterial
    ['black rear cover']: THREE.MeshStandardMaterial
    ['rear guard inside']: THREE.MeshStandardMaterial
    ['black 2']: THREE.MeshStandardMaterial
    ['black 4']: THREE.MeshStandardMaterial
    ['black 5']: THREE.MeshStandardMaterial
    ['black front mud guard']: THREE.MeshStandardMaterial
    indicator_led: THREE.MeshStandardMaterial
    talight_off: THREE.MeshStandardMaterial
    ['silver sprint ebt left']: THREE.MeshStandardMaterial
    ['xtreme logo']: THREE.MeshStandardMaterial
    ['body paint red logo']: THREE.MeshStandardMaterial
    ['silver red tank']: THREE.MeshStandardMaterial
    ['tail right red']: THREE.MeshStandardMaterial
    ['tail left red']: THREE.MeshStandardMaterial
    ['silver sprint ebt right']: THREE.MeshStandardMaterial
    right_125R_red: THREE.MeshStandardMaterial
    left_125R_red: THREE.MeshStandardMaterial
    ['body paint red']: THREE.MeshStandardMaterial
    ['black.001']: THREE.MeshStandardMaterial
  }
  //animations: GLTFAction[]
  
}

interface XtremeProps {
  color: string;
};

const Xtreme: React.FC<XtremeProps> = ({ color }) => {
  const { nodes, materials } = useGLTF('/models/xtremetest.glb') as GLTFResult;
  const meshRef = useRef<THREE.Mesh>(null);

  useEffect(() => {
    if (meshRef.current) {
      const material = materials['body paint red'];
      if (material instanceof THREE.MeshStandardMaterial) {
        material.color.set(color);
      }
    }
  }, [color, materials]);

  return (
    <group dispose={null}>
      <group rotation={[0, 0, -0.006]} scale={0.001}>
        <mesh geometry={nodes.Mesh_1005.geometry} material={materials['bolt silver']} />
        <mesh geometry={nodes.Mesh_1005_1.geometry} material={materials.black} />
      </group>
      <mesh geometry={nodes.bronze_parts.geometry} material={materials['light bronze']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.button_left.geometry} material={materials.buttons} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.button_right.geometry} material={materials['engine red']} rotation={[0, 0, -0.006]} scale={0.001} />
      <group rotation={[0, 0, -0.006]} scale={0.001}>
        <mesh geometry={nodes.Circle002.geometry} material={materials['chain colour 2']} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials['chain colour 1']} />
      </group>
      <mesh geometry={nodes.chrome_parts.geometry} material={materials.chrome} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.drl_inside.geometry} material={materials['drl 1']} rotation={[0, 0, -0.006]} scale={0.001} />
      <group rotation={[0, 0, -0.006]} scale={0.001}>
        <mesh geometry={nodes.Mesh_25009.geometry} material={materials['engine black']} />
        <mesh geometry={nodes.Mesh_25009_1.geometry} material={materials['engine silver']} />
        <mesh geometry={nodes.Mesh_25009_2.geometry} material={materials.resevoir_glass} />
        <mesh geometry={nodes.Mesh_25009_3.geometry} material={materials['engine red']} />
      </group>
      <mesh geometry={nodes.front_disc_brake.geometry} material={materials['front disc']} rotation={[Math.PI / 2, -0.006, 0]} scale={[0.001, 0, 0.001]} />
      <mesh geometry={nodes.front_left_shock.geometry} material={materials['black fork left']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.front_right_shock.geometry} material={materials['black fork right']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.front_tyre_sidewall.geometry} material={materials['front tyre side wall']} rotation={[0, 0, -0.006]} scale={1.018} />
      <mesh geometry={nodes.front_tyre_threads.geometry} material={materials['front tyre thread']} rotation={[0, 0, -0.006]} scale={1.001} />
      <mesh geometry={nodes.headlight_assembly_black.geometry} material={materials.black} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.headlight_glass.geometry} material={materials['headlight glass']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.headlight_emission.geometry} material={materials['lens light off']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.headlight_part_1.geometry} material={materials.black} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.headlight_part_3.geometry} material={materials['headlight glass']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.hero_black_left.geometry} material={materials['black hero left']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.hero_black_right.geometry} material={materials['black hero right']} rotation={[0, 0, -0.006]} scale={0.001} />
      <group rotation={[0, 0, -0.006]} scale={0.001}>
        <mesh geometry={nodes.Mesh_25006.geometry} material={materials.black} />
        <mesh geometry={nodes.Mesh_25006_1.geometry} material={materials['headlight glass']} />
        <mesh geometry={nodes.Mesh_25006_2.geometry} material={materials.chrome} />
      </group>
      <mesh geometry={nodes.number_plate_front.geometry} material={materials['number plate']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.number_plate_rear.geometry} material={materials['number plate']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.rear_sporcket.geometry} material={materials['rear sprocket']} rotation={[Math.PI / 2, -0.17, 0]} scale={0.001} />
      <mesh geometry={nodes.mono_shock_suspension.geometry} material={materials['sprint white']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.rear_swing_arm_parts.geometry} material={materials['engine silver']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.rear_tyre_sidewall.geometry} material={materials['rear tyre side wall']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.rear_tyre_thread.geometry} material={materials['rear tyre thread']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.red_resevoir.geometry} material={materials['red resevoir']} rotation={[0, 0, -0.006]} scale={0.001} />
      <group rotation={[0, 0, -0.006]} scale={0.001}>
        <mesh geometry={nodes.Mesh_25008.geometry} material={materials.black} />
        <mesh geometry={nodes.Mesh_25008_1.geometry} material={materials['side reflector']} />
      </group>
      <mesh geometry={nodes.rims.geometry} material={materials.grey} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.seat.geometry} material={materials['seat grey']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.silver_parts.geometry} material={materials.foot_peg} rotation={[0, 0, -0.006]} scale={0.001} />
      <group rotation={[0, 0, -0.006]} scale={0.001}>
        <mesh geometry={nodes.Mesh_8001.geometry} material={materials.black} />
        <mesh geometry={nodes.Mesh_8001_1.geometry} material={materials['speedo glass']} />
        <mesh geometry={nodes.Mesh_8001_2.geometry} material={materials.speedometer} />
        <mesh geometry={nodes.Mesh_8001_3.geometry} material={materials['speedo black']} />
      </group>
      <mesh geometry={nodes.tail_light_glass.geometry} material={materials['tail light']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.tail_light_inside.geometry} material={materials['tail light red']} rotation={[0, 0, -0.689]} scale={[0.002, 0.032, 0.032]} />
      <mesh geometry={nodes.taillight.geometry} material={materials['tailight black']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.tank.geometry} material={materials['TANK BLACK']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.mirror.geometry} material={materials.mirror} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.black_parts_2.geometry} material={materials['black 3']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.muffler_cover.geometry} material={materials['light bronze']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.Rear_tyre_side_cover.geometry} material={materials['black rear cover']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.rear_guard_inside.geometry} material={materials['rear guard inside']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.rear_mud_guard.geometry} material={materials.black} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.exhaust_pipe.geometry} material={materials['black 2']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.black_parts_3.geometry} material={materials['black 4']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.black_parts_5.geometry} material={materials['black 5']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.black_parts_4.geometry} material={materials['black front mud guard']} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.single_channel_abs.geometry} material={materials.black} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.indicator_led.geometry} material={materials.indicator_led} rotation={[0, 0, -0.006]} scale={0.001} />
      <mesh geometry={nodes.tailight_emission.geometry} material={materials.talight_off} />
      <group rotation={[0, 0, -0.006]} scale={0.001}>
        <mesh geometry={nodes.BSurfaceMesh034.geometry} material={materials['silver sprint ebt left']} />
        <mesh geometry={nodes.BSurfaceMesh034_1.geometry} material={materials['xtreme logo']} />
        <mesh geometry={nodes.BSurfaceMesh034_2.geometry} material={materials['body paint red logo']} />
        <mesh geometry={nodes.BSurfaceMesh034_3.geometry} material={materials['silver red tank']} />
        <mesh geometry={nodes.BSurfaceMesh034_4.geometry} material={materials['tail right red']} />
        <mesh geometry={nodes.BSurfaceMesh034_5.geometry} material={materials['tail left red']} />
        <mesh geometry={nodes.BSurfaceMesh034_6.geometry} material={materials['silver sprint ebt right']} />
        <mesh geometry={nodes.BSurfaceMesh034_7.geometry} material={materials.right_125R_red} />
        <mesh geometry={nodes.BSurfaceMesh034_8.geometry} material={materials.left_125R_red} />
        <mesh geometry={nodes.BSurfaceMesh034_9.geometry} material={materials['body paint red']} ref={meshRef} />
      </group>
      <mesh geometry={nodes.black_parts_1.geometry} material={materials['black.001']} rotation={[0, 0, -0.006]} scale={0.001} />
    </group>
  )
}



useGLTF.preload('/models/xtremetest.glb')

export default Xtreme; 